### ISSUE TITLE
Template cannot be created with lein-ancient 0.6.1 in lein profiles

### ISSUE THREAD

**Issue by szamuboy** [tailrecursion/hoplon-template#4]
Hi,

I simply tried to create a new hoplon project that resulted in an exception, see [gist](https://gist.github.com/szamuboy/ef90dbf4200d212a75a7#file-gistfile1-sh-session).

I tracked down the problem: when I removed the lein-ancient 0.6.1 from my leiningen profile the issue was gone.

How to reproduce:
Set your leiningen profile to [profiles.clj](https://gist.github.com/szamuboy/484baf3d5b38002e2021#file-profiles-clj) and create a new hoplon project.

**Comment by mynomoto** [comment]
I just released a new version, this should be fixed now.
