### ISSUE TITLE
update for boot 2

### ISSUE THREAD

**Issue by flyboarder** [tailrecursion/hoplon-template#6]
please update template for boot 2

**Comment by micha** [comment]
We could make a branch for it, but I don't know how useful that would be? The lein template system works by pulling from Clojars, so until we are ready for an official release we probably don't want to change the templates (it would break things for people using the current release version).

We'll try to update the templates for the 6.0.0 release in a way that hopefully not break anything for anybody. (We may make a `hoplon6-template`, even.)
